# Generated by Django 4.1.2 on 2022-10-27 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlackList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=200)),
                ('ip_address', models.TextField()),
                ('tf', models.CharField(choices=[('T', '블랙'), ('F', '블랙해지')], max_length=1)),
                ('note', models.TextField()),
            ],
        ),
    ]
