# Generated by Django 4.1.2 on 2022-10-27 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlackList',
        ),
    ]
