# Generated by Django 4.1.3 on 2022-12-29 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("live", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chattingdata",
            name="time",
            field=models.DateTimeField(default="2022-12-29 05:35:14"),
        ),
    ]
