# Generated by Django 4.1.3 on 2022-12-29 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("live", "0004_alter_chattingdata_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chattingdata",
            name="time",
            field=models.DateTimeField(default="2022-12-29 05:37:48"),
        ),
        migrations.AlterField(
            model_name="live",
            name="src",
            field=models.TextField(default=""),
        ),
    ]
