# Generated by Django 4.1.2 on 2022-10-27 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0005_live'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlackList',
        ),
        migrations.DeleteModel(
            name='ChattingBlackList',
        ),
        migrations.DeleteModel(
            name='ChattingWarning',
        ),
        migrations.DeleteModel(
            name='Live',
        ),
    ]
