# Generated by Django 4.1.2 on 2022-10-28 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0007_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='live',
            name='sub_name',
        ),
        migrations.AlterField(
            model_name='chattingdata',
            name='time',
            field=models.DateTimeField(default='2022-10-28 02:09:14'),
        ),
    ]
