# Generated by Django 4.1.3 on 2022-11-28 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("live", "0037_alter_chattingdata_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chattingdata",
            name="time",
            field=models.DateTimeField(default="2022-11-28 08:45:47"),
        ),
    ]
