# Generated by Django 4.1.2 on 2022-10-28 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_managers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
