# Generated by Django 4.1.2 on 2022-10-28 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0004_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sub_name', models.CharField(max_length=200)),
                ('user_id', models.CharField(max_length=200)),
                ('pw', models.CharField(max_length=200)),
                ('phon', models.CharField(max_length=14)),
                ('email', models.CharField(max_length=200)),
                ('sub_name_tf', models.CharField(choices=[('T', 'T'), ('F', 'F')], default='T', max_length=2)),
            ],
        ),
    ]
