# Generated by Django 4.1.3 on 2022-11-28 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="sub_name_tf",
        ),
    ]
