# Generated by Django 4.1 on 2022-09-27 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='videoCategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='video.videocategory'),
        ),
    ]
