# Generated by Django 4.1 on 2022-09-28 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_video_url_small_alter_video_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
    ]
