# Generated by Django 4.1 on 2022-09-29 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0004_delete_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('cdate', models.DateTimeField()),
                ('udate', models.DateTimeField()),
                ('user_id', models.CharField(max_length=200)),
                ('run_time', models.CharField(max_length=100)),
                ('url', models.FileField(upload_to='video')),
                ('url_small', models.FileField(upload_to='video_small')),
                ('content', models.TextField()),
                ('Thumbnail', models.ImageField(upload_to='thumbnail')),
                ('run_count', models.IntegerField()),
                ('videoCategory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='video.videocategory')),
            ],
        ),
    ]
