# Generated by Django 4.1 on 2022-09-30 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0005_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='Thumbnail',
            new_name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='video',
            name='run_time',
        ),
        migrations.AlterField(
            model_name='video',
            name='cdate',
            field=models.DateTimeField(default='03:47:33'),
        ),
        migrations.AlterField(
            model_name='video',
            name='run_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='video',
            name='udate',
            field=models.DateTimeField(default='03:47:33'),
        ),
    ]
