# Generated by Django 4.1 on 2022-09-30 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0006_rename_thumbnail_video_thumbnail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='cdate',
            field=models.DateTimeField(default='2022/09/30 04:01:48'),
        ),
        migrations.AlterField(
            model_name='video',
            name='udate',
            field=models.DateTimeField(default='2022/09/30 04:01:48'),
        ),
    ]
