# Generated by Django 4.1 on 2022-10-04 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0010_remove_video_thumbnail_alter_video_cdate_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
    ]
