# Generated by Django 4.1 on 2022-10-04 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0011_delete_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('cdate', models.DateTimeField(default='2022-10-04 08:32:28')),
                ('udate', models.DateTimeField(default='2022-10-04 08:32:28')),
                ('user_id', models.CharField(max_length=200)),
                ('url', models.FileField(upload_to='video')),
                ('url_small', models.FileField(upload_to='video_small')),
                ('content', models.TextField()),
                ('thumbnail', models.ImageField(upload_to='thumbnail')),
                ('thumbnail_small', models.ImageField(upload_to='thumbnail_small')),
                ('run_count', models.IntegerField(default=0)),
                ('videoCategory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='video.videocategory')),
            ],
        ),
    ]
